### ISSUE TITLE
"Catalan transltion" (ca) should be reviewed

### ISSUE THREAD

**Issue by chtiland** [dregad/dokuwiki-plugin-addnewpage#101]
There's something quite strange in this translation...

**Comment by dregad** [comment]
If you say so... I don't speak Catalan, so if you do please fix it as appropriate and I will gladly merge a pull request.

As it stands, this issue is useless as it does not even say what is wrong.

**Comment by dregad** [comment]
Ah never mind I see what you mean now - there is some Russian spam that was introduced with #100. I'll revert the change.
