### ISSUE TITLE
pagename contains a colon ':'

### ISSUE THREAD

**Issue by ronanviel** [dregad/dokuwiki-plugin-addnewpage#50]
When the pagename you type in the form contains a colon character ':', it creates a namespace with the name right of the colon. Is it a bug or a feature? The documentation on dokuwiki.org is not clear about this point.

**Comment by samwilson** [comment]
Hm, good point. Perhaps the form should prevent the entry of a colon all together? But then, maybe it's useful to be able to create subnamespaces at that point too? That'd be mainly for more advanced users, though, who would know they could always just type in the URL.

So I'd say it's currently a feature :-) but chould perhaps be removed for nicer operation. What do you think?

**Comment by ronanviel** [comment]
Well, I currently tell my users that's a feature :-) But actually the user who discovered it, wanted to create an article with a colon in the title. I gave him a simple workaround but it will have the same issue with different users in the future. 
I would personally prefer to avoid namespace creation with this plugin because it could result in unintended results. On my site, I'm using your plugin to create pages in a specific namespace which content is listed using the nspages plugin but it doesn't list pages in sub-namespaces.

**Comment by dregad** [comment]
Closing stale issue, sticking with @samwilson's statement that it's a feature, until proven otherwise 😉
