### ISSUE TITLE
pre-fill the page-title box

### ISSUE THREAD

**Issue by vincentkersten** [dregad/dokuwiki-plugin-addnewpage#51]
Hi! Thank you for creating this , it really works very well in our workflow :)
Question though: is there a way to prefill the field (in my case i would like all docs to start with an ISO date)
Something like (in ascii art):
[2015-12-23 ChangePageTitle  ]   [Add page]

Thank you in advance, regards,

  Vincent

**Comment by mrclschstr** [comment]
I'd appreciate this feature as well :smiley:

**Comment by dregad** [comment]
This should be covered by #72.
