### ISSUE TITLE
“Hide namespace selection” option on per-instance basis

### ISSUE THREAD

**Issue by marcink** [dregad/dokuwiki-plugin-addnewpage#53]
Is there a way to control the “Hide namespace selection” option on a per-instance basis as opposed to site-wide?

**Comment by dregad** [comment]
Not sure what you mean by "per instance". Please clarify.

**Comment by marcink** [comment]
It's been 7 years since I posted that question :).   I no longer manger that wiki instance (and don't have a working instance to do any testing on), but from what I remember there is a site-wide configuration option (accessed through admin configuration page) called "Hide namespace selection".  I was looking to change that option on a per-use basis, so as an argument to the {{NEWPAGE}} call.

**Comment by dregad** [comment]
> It's been 7 years since I posted that question :). 

Well, this plugin's been abandonware since ~ 2016, and I just took over, sorry for the noise 😉 

Thanks for the feedback. I think this may be covered by PR #72

**Comment by marcink** [comment]
Kudos to anyone that picks up a plugin to maintain it.  Yes, it seems like the new `?` option would do the job.
