### ISSUE TITLE
Enhance plugin adding 

### ISSUE THREAD

**Issue by anacaona83** [dregad/dokuwiki-plugin-addnewpage#61]
Hello, Is it possible to enhance the plugin adding a set of new pages instead of adding only one page?
With basic text into (something like "Page is currently being drafted. " ) and automatic registration?

I need to create a set 200 pages so I did generate the .txt whith database query but i can't create their associated dokuwiki metadata so the pages can't be edited. Really need a plugin and don't know how to develop it.

**Comment by dregad** [comment]
This is outside the scope of this plugin.
