### ISSUE TITLE
@NS@ not working?

### ISSUE THREAD

**Issue by dcbell** [dregad/dokuwiki-plugin-addnewpage#65]
I assume I'm missing something simple, but I can't figure it out. I'm trying to create a skeleton framework that I can reuse for various things. As part of this skeleton i have a namespace "site_template". Somewhere in there, I'm using the addnewpage plugin and I don't want to hardcode the location, since the new page should be created relative to the current location (who point of the skeletal structure). I was originally trying "{{NEWPAGE>.:network}}" to put it in the network namespace under the current namespace (site_template). But that wasn't working. Then I got to looking at namespace templates. So now i'm trying "{{NEWPAGE>@NS@:network}}" But that just creates a namespace "ns:network" at the root. Am I missing something?

**Comment by mrclschstr** [comment]
Try using capital letters for the variable. Using `{{NEWPAGE>@NS@}}` works fine for me in my template.

**Comment by dregad** [comment]
Closing stale issue. Feel free to reopen if needed.
