### ISSUE TITLE
Useheadings for selection

### ISSUE THREAD

**Issue by TobiasSchellhorn** [dregad/dokuwiki-plugin-addnewpage#7]
Pls add an option that i can use headings instead of namespace

**Comment by Valiantiam** [comment]
Would love to see this done yet.

**Comment by dregad** [comment]
I'm not sure I understand what the requirement is here. Please provide a more detailed specification.

**Comment by dregad** [comment]
Since nobody came up with a clear description of the feature, I'm closing this. Feel free to reopen if you can provide a specification.
