### ISSUE TITLE
possible conflict with struct plugin?

### ISSUE THREAD

**Issue by kulaw327** [dregad/dokuwiki-plugin-addnewpage#73]
When I activate add new page plugin, the table generated by struct plugin does not appear on the page. 

Any advice would be appreciated.

**Comment by andreasferber** [comment]
Are you by chance using the bootstrap3 template? See [https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/321](url). You can find the missing struct data in the "Add New Page" dropdown in your navigation bar.

**Comment by dregad** [comment]
Closing stale issue. Feel free to reopen if problem persists.
