### ISSUE TITLE
getInfo() not implemented for Hogfather

### ISSUE THREAD

**Issue by gadzuuks** [dregad/dokuwiki-plugin-addnewpage#83]

**Comment by Autumnf0x** [comment]
The same

**Comment by dregad** [comment]
It's alive again 😄 

I'm not sure I understand what the problem is, can you please clarify and provide steps to reproduce ?

**Comment by dregad** [comment]
Closing due to lack of feedback. Feel free to reopen with a clarification of what the problem is.
