### ISSUE TITLE
Add placeholder= to indicate field requires a page name

### ISSUE THREAD

**Issue by bradgillap** [dregad/dokuwiki-plugin-addnewpage#88]
Hello, thank you for the plugin.

Just a recommendation

on line 103 of syntax.php

```
. DOKU_TAB . DOKU_TAB . '<input class="edit" type="text" name="title" size="20" maxlength="255" tabindex="2" placeholder="Page Name" />' . DOKU_LF
```

Would also recommend adding some space to the form-control class but that's just nitpicking.

```
.form-control {
margin-bottom: 1em;
}
```

fancy

![image](https://user-images.githubusercontent.com/1094081/133534567-135416f5-e700-4815-8e11-48c13ca2fafe.png)

**Comment by dregad** [comment]
> Would also recommend adding some space to the form-control class but that's just nitpicking.
> 
> ```
> .form-control {
> margin-bottom: 1em;
> }
> ```

I'm not sure where this `form-control` class is coming from - it is not part of the markup generated by the plugin.

I tried adding the proposed 1em margin to the *addnewpage* div, but it does not seem to make any difference when the page renders (at least with the default *dokuwiki* template).
