### ISSUE TITLE
New maintainer ?

### ISSUE THREAD

**Issue by dregad** [dregad/dokuwiki-plugin-addnewpage#93]
This plugin has been unattended for many years, with community contributions just sitting there.

I need some fixes for PHP 8 compatibility, so I asked @samwilson if he was OK to let me help with maintenance or even take over the plugin.

He would like to make sure the community is fine with that, so if you are please vote with a 👍

**Comment by splitbrain** [comment]
See also https://www.dokuwiki.org/devel:adoption If the original author agrees, no further steps are necessary. The community is always happy when a plugin is maintained :wink:

**Comment by samwilson** [comment]
Thanks for taking it on @dregad! Sorry if I seemed hesitant when you contacted me about it. I've had various bad-faith requests to take over WordPress plugins in the past, so I'm sort of nervous!

But this all looks good, and I'm very glad to see the plugin have a new life. I no longer use Dokuwiki, but it will always hold a place in my heart! :-)

I'll transfer this repo to you (you just need to delete your fork first). And as this is a fork itself (of https://github.com/hamstar/dokuwiki-plugin-addnewpage ), it might be worth you requesting (to GitHub) to de-fork it, so it's a base repo.

**Comment by dregad** [comment]
Thanks @samwilson. I just nuked my fork, so you can go ahead with the transfer. 

> it might be worth you requesting (to GitHub) to de-fork it, so it's a base repo

Yes, I was planning to do that.

**Comment by dregad** [comment]
> > it might be worth you requesting (to GitHub) to de-fork it, so it's a base repo
> 
> Yes, I was planning to do that.

@samwilson FYI, GitHub support have just made the change, this repo is now the parent of the network's tree
https://github.com/dregad/dokuwiki-plugin-addnewpage/network/members
