### ISSUE TITLE
date 2016-12-23?

### ISSUE THREAD

**Issue by fiwswe** [dregad/dokuwiki-plugin-addnewpage#94]
The current version of the plugin has the date 2016-12-23 in plugin.info.txt. That seems highly improbable given #93 and the recent commits.

**Comment by dregad** [comment]
As mentioned in the tagged commit 959a1256863d65f6ed151846107431d6c383e9b4, I just marked a release as of the last change committed by the previous maintainer.

I'm still catching up with changes backlog and planning a new release hopefully in the coming days, but currently stuck with resolving merge conflicts in #72.

Please bear with me.

**Comment by fiwswe** [comment]
Well, from the point of view of a user I saw an update was available and then I get a version that is seemingly more than 6 years old. That made me look for a problem first on the [plugin page](https://www.dokuwiki.org/plugin:addnewpage), then in the code. Am I the only one confused by this?

Now that you have explained your reasoning it makes sense — kind of. I would have used the current date (2023-05-07) though.

**Comment by dregad** [comment]
Well in hindsight I should not have committed to the master branch or pushed that tag, until I was ready with all the changes.

The plan was to finalize everything on Sunday so both the 2016-12-23 and a new 2023-05-07 tags would have been pushed at the same time, but then real life got in the way...

Apologies for the inconvenience.

**Comment by dregad** [comment]
@fiwswe I published 2023-05-10 just now, to fix the mess and avoid others the trouble you went through... I'll deal with the remaining pending issues later.
